// components/Confession.vue
<script lang='ts' setup>
import { NCard, NIcon } from 'naive-ui';
import { Globe } from '@vicons/fa';
import chroma from 'chroma-js';

const {
	title,
	color,
	content,
	websiteLink,
	websiteName,
	withWebsite
} = defineProps<{
	title: string,
	color: string,
	content: string,
	websiteLink: string | null,
	websiteName: string | null,
	withWebsite: boolean
}>();
const isDark = chroma(color).hsl()[2] < 0.45;
const changedColor = isDark ? 'white' : 'black';

const NCardStyle = {
	backgroundColor: color,
	'--n-title-text-color': `${changedColor} !important`
};

</script>
<template>
	<n-card
		:title="title"
		:style="NCardStyle"
		:header-style="{ fontSize: '1.5rem', color: changedColor }"
		:content-style="{ fontSize: '1rem', color: changedColor }"
	>
		{{ content }}
		<div
			v-if="withWebsite"
			class="link-item"
			:style="{ color: changedColor }"
		>
			<div class="_link">
				<n-icon>
					<Globe :style="{ filter: `invert(${isDark ? 1 : 0})` }" />
				</n-icon>
				Link:
			</div>
			<a
				:href="
					!websiteLink?.startsWith('http')
						? websiteLink?.replace(websiteLink ?? '', 'https://'.concat((websiteLink ?? '')))
						: websiteLink
				"
				target="_blank"
				class="hover-link"
				:style="{ color: changedColor }"
			>
				{{ websiteName }}
			</a>
		</div>
	</n-card>
</template>

<style lang="scss">
.link-item {
	margin-block: 1rem;
	display: flex;
	gap: 6px;
}

._link {
	display: flex;
	align-items: center;
	gap: 6px;
}

</style>

// components/Confession.tsx
import React from 'react';
import { Stack, Grid, Box, Link, Flex, Button } from '@chakra-ui/react';
import { FaEnvelope, FaGlobe } from 'react-icons/fa';
import chroma from 'chroma-js';
import { ConfessionData } from 'utils/interfaces';

export const Confession: React.FC<ConfessionData> = ({ title, content, color, withWebsite, websiteLink, websiteName }) => {
	const isDark = chroma(color).hsl()[2] < 0.42;
	return (
		<Stack>
			<Grid bg={color} borderRadius={20} pt={3} pb={5} px={6} gap={3} color={isDark ? 'white' : 'black'} flexWrap="wrap">
				<Box pt={2} fontSize='1.5rem'> {title} </Box>
				<Box>
					{content} {' '}
				</Box>
				<Flex // @ts-ignore
					visibility={!withWebsite ? "hidden" : ""}
					alignItems="center"
					gap={1}
				>
					<FaGlobe />
					Link: {' '}
					<Link href={websiteLink} isExternal>
						<span className="link">
							<Button size='xs'>{websiteName}</Button>
						</span> 
					</Link> 
					<style jsx scoped>
						{`
							.link {
								color: ${isDark ? "white" : "black"} !important;
								transition: filter 150ms;
							}
							.link:hover {
								filter: brightness(.8)
							}
						`}
					</style>
				</Flex>
			</Grid>
		</Stack>
	);
};
