// client/src/components/Modal.vue
<template>
  <div class="modal-create" uk-modal>
    <div class="uk-modal-dialog uk-modal-body">
      <h2 class="uk-modal-title">Create Confession</h2>
      <form @submit="submitForm">
        <div class="input">
          <label for="title" class="input-label">Title</label>
          <input 
            type="text" 
            class="uk-input" 
            name="title" 
            v-model="title" 
            @blur="validateTitle" 
            placeholder="Title"
          >          
          <span class="error">{{ titleRequired }} </span>
        </div>
        <div class="input">
          <label for="content" class="input-label">Content</label>
          <textarea 
            name="content" 
            maxlength="500" 
            rows="10" 
            class="uk-textarea" 
            v-model="content" 
            placeholder="Content" 
            @blur="validateContent" 
          />
          <span class="error">{{ contentRequired }} </span>
        </div>
        <div class="input-checkbox">
          <input type="checkbox" name="withWebsite" v-model="withWebsite" @change="disableOptionalInputs">
          <label for="withWebsitLink">With website link?</label>
        </div>
        <div class="input">
          <label for="websiteName" class="input-label">Website Name</label>
          <input type="text" class="uk-input optional" name="websiteName" disabled required placeholder="Put your website name" v-model="websiteName">           
        </div>
        <div class="input">
          <label for="websiteLink" class="input-label">Website Link</label>
          <input type="text" class="uk-input optional" name="websiteLink" disabled required placeholder="Put your website link" v-model="websiteLink">
          <span class="error"> {{ linkOnError }} </span>           
        </div>
        <button type="submit"> {{ !isCreating ? "Create Confession" : "Creating..." }} </button>
      </form> 
    </div>
  </div>
</template>

<script lang="ts">
import '@/styles/modal.scss'
import { defineComponent } from "vue";
import UIkit from 'uikit'
import { containsOnlySpaces } from "@/utils/containsOnlySpaces"
import { createConfession } from "@/utils/createConfession"
import { randomColor } from '@/utils/randomColor'

export function openModal() {
  UIkit.modal(".modal-create").show()
  // @ts-ignore
  document.querySelector("#modal-create").scrollTo(0,0)
  // @ts-ignore
  document.querySelector("[type='checkbox']").checked =false

  const nodes = document.querySelectorAll(".optional")
  nodes.forEach(x => {
    x.setAttribute("disabled", "")
  })                
}

export default defineComponent({
  name: "Modal",
  data(){
    return {
      title: "",
      content: "",
      withWebsite: false,
      websiteName: "",
      websiteLink: "",
      titleRequired: "",
      contentRequired: "",
      isLinkValidated: false,
      linkOnError: "",
      isCreating: false
    }
  },
  methods: {
    backToDefault() {
      this.title = ""
      this.content = ""
      this.withWebsite = false
      this.websiteLink = ""
    },
    validateTitle(){
      if (this.title == "") {
        this.titleRequired = "Title is required"
      } else if (containsOnlySpaces(this.title)) {
        this.titleRequired = "Cannot contain only spaces"
      } else {
        this.titleRequired = ""
      }
    },
    validateContent(){
      if (this.content == "") {
        this.contentRequired = "Content is required"
      } else if (containsOnlySpaces(this.content)) {
        this.contentRequired = "Cannot contain only spaces"
      } else {
        this.contentRequired = ""
      }
    },
    async submitForm(e: any){
      e.preventDefault()
      this.isCreating = true
      if ((this?.title != "" && !containsOnlySpaces(this.title)) && (this.content != "" && !containsOnlySpaces(this.content))) {      
        if (this.withWebsite) {
          await createConfession({
            title: this.title,
            content: this.content,
            color: randomColor(),
            withWebsite: this.withWebsite,
            websiteName: this.websiteName,
            websiteLink: this.websiteLink
          })
        } else {        
          await createConfession({
            title: this.title,
            content: this.content,
            color: randomColor(),
            withWebsite: this.withWebsite
          })
        }
        this.isCreating = false
        UIkit.modal("#modal-create").hide()
      } else {
        this.validateTitle()
        this.validateContent()
      }
      this.backToDefault()
    },
    disableOptionalInputs(){
      const nodes = document.querySelectorAll(".optional")
      if (!this?.withWebsite) {
        nodes.forEach(x => {
          x.setAttribute("disabled", "")
        })                
      } else {
        nodes.forEach(x => {
          x.removeAttribute("disabled")
        })                        
      }
    }
  }
})
</script>

// components/Modal.tsx
import { useState, useEffect } from "react"
import {
  Box,
  Button,
  Flex,
  Stack,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
  FormControl,
  FormLabel,
  FormErrorMessage,
  Input,
  Textarea,
  Checkbox,
} from "@chakra-ui/react"
import { Formik, Field } from "formik"
import { isSpacesOnly } from "utils/isSpacesOnly"

// @ts-ignore
export const ConfessionModal = props => {
  const [withWebsite, toggleWithWebsite] = useState<boolean>(false)

  return (
    <Modal isOpen={props.isOpen} onClose={props.onClose}>
      <ModalOverlay />
      <ModalContent>
        <Formik
          initialValues={{
            title: "",
            content: "",
            withWebsite: false,
            websiteName: "",
            websiteLink: ""
          }}
          onSubmit={async (values) => {
            await fetch("/api/create", {
              method: "POST",
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify(values)
            })
            props.onClose()
            document.location.reload()
          }}
        >
          {({ handleSubmit, errors, touched }) => (
            <form onSubmit={handleSubmit}>
              <ModalHeader fontSize={24} fontWeight="bolder">
                Create Confession
              </ModalHeader>
              <ModalCloseButton />
              <ModalBody>
                <Flex flexDirection="column" gap={6}>
                  <Stack spacing={4}>
                    <FormControl isInvalid={!!errors.title && touched.title}> 
                      <FormLabel fontWeight="bold" fontSize={20} htmlFor="title">
                        Title
                      </FormLabel>
                      <Field 
                        as={Input} 
                        name="title" 
                        placeholder="Title" 
                        type="text"
                        validate={(value: string) => {
                          let error
                          if (value === "") {
                            error = "Title is required"
                          } else if (isSpacesOnly(value)) {
                            error = "Cannot contain only spaces"
                          }
                          return error
                        }} 
                      /> 
                      <FormErrorMessage>{errors.title}</FormErrorMessage>
                    </FormControl>
                    <FormControl isInvalid={!!errors.content && touched.content}>
                      <FormLabel fontWeight="bold" fontSize={20} htmlFor="content">
                        Content
                      </FormLabel>
                      <Field
                        as={Textarea}
                        type="text"
                        placeholder="Content"
                        name="content"
                        validate={(value: string) => {
                          let error
                          if (value === "") {
                            error = "Content is required"
                          } else if (isSpacesOnly(value)) {
                            error = "Cannot contain only spaces"
                          }
                          return error
                        }}
                      />
                      <FormErrorMessage>{errors.content}</FormErrorMessage>
                    </FormControl>
                  </Stack>
                  <Field
                    as={Checkbox}
                    isChecked={withWebsite}
                    onChange={() =>
                      // @ts-ignore
                      toggleWithWebsite(() => (withWebsite = !withWebsite))
                    }
                    name="withWebsite"
                  >
                    With website?
                  </Field>
                  <Stack spacing={4}>
                    <FormControl isInvalid={!!errors.websiteName}>
                      <FormLabel fontWeight="bold" fontSize={20} htmlFor="websiteName">
                        Website Name
                      </FormLabel>
                      <Field
                        as={Input}
                        type="text"
                        placeholder="Put your website name"
                        isDisabled={!withWebsite}
                        name="websiteName"
                        validate={(value: string) => {
                          let error
                          if (withWebsite) {
                            if (value === "") {
                              error = "Website name is required"
                            } else if (isSpacesOnly(value)) {
                              error = "Cannot contain only spaces"
                            }                            
                          }
                          return error
                        }} 
                      />
                      <FormErrorMessage>{errors.websiteName}</FormErrorMessage>
                    </FormControl>
                    <FormControl isInvalid={!!errors.websiteLink && touched.websiteLink && withWebsite}>
                      <FormLabel fontWeight="bold" fontSize={20} htmlFor="websiteLink">
                        Website Link
                      </FormLabel>
                      <Field
                        as={Input}
                        type="text"
                        placeholder="Put your website link"
                        isDisabled={!withWebsite}
                        name='websiteLink'
                        validate={(value: string) => {
                          let error
                          if (withWebsite) {
                            if (value === "") {
                              error = "Website link is required"
                            } else if (isSpacesOnly(value)) {
                              error = "Cannot contain only spaces"
                            }                            
                          }
                          return error
                        }} 
                      />
                      <FormErrorMessage>{errors.websiteLink}</FormErrorMessage>
                    </FormControl>
                  </Stack>
                </Flex>
              </ModalBody>
              <ModalFooter>
                <Button type="submit">Submit</Button>
              </ModalFooter>
            </form>
          )}
        </Formik>
      </ModalContent>
    </Modal>
  )
}
