// components/Navbar.vue
<script lang="ts" setup>
import { NavigationGuardNext, RouteLocationNormalized } from 'vue-router';
import { NButton } from 'naive-ui';

const router = useRouter();
const path = ref<string>(window.location.pathname);
const isOpen = ref<boolean>(false);

router.beforeEach((
	to: RouteLocationNormalized,
	from: RouteLocationNormalized,
	next: NavigationGuardNext
) => {
	path.value = to.path;
	next();
});

</script>

<template>
	<div class="navbar">
		<NuxtLink
			class="title"
			:to="path !== '/welcome' ? '/home' : '/welcome'"
		>
			Confession Wall
		</NuxtLink>
		<NuxtLink
			v-if="path !== '/welcome'"
			to="/about"
			class="hover-link"
		>
			About
		</NuxtLink>
		<n-button
			type="info"
			:style="{
				visibility: path !== '/about' && path !== '/welcome' ? 'visible' : 'hidden'
			}"
			@click="isOpen = true"
		>
			Create
		</n-button>
	</div>
	<ConfessModal :show="isOpen" @close="isOpen = false" />
</template>

<style scoped lang="scss">
.navbar {
	display: flex;
	align-items: center;
	justify-content: space-between;
	margin: 1.25rem 9rem;
	.title {
		font-size: 1.5rem;
		font-weight: bold;
	}
}
</style>

// components/Navbar.tsx
import Link from "next/link";
import { useRouter } from "next/router";
import { Box, Button, Flex, useDisclosure } from "@chakra-ui/react";
import navbar from "styles/navbar.module.scss";
import { ConfessionModal } from "components/Modal";

const Navbar = () => {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const router = useRouter();
  const isWelcomePage = (path: string): boolean => path === "/welcome";

  return (
    <Box>
      <Flex
        mx="calc(3rem + 30px)"
        justifyContent="space-between"
        alignItems="center"
      >
        <Link
          href={router.pathname === "/welcome" ? "/welcome" : "/home"}
          className={navbar.link}
        >
          <div className={navbar.h2}>Confession Wall</div>
        </Link>
        <Link href="/about">
          <Box
            className={navbar.aboutlink}
          // @ts-ignore
            visibility={isWelcomePage(router.pathname) ? "hidden" : ""}
          >
            About
          </Box>
        </Link>
        <Button
          onClick={onOpen}
          colorScheme="blue"
          // @ts-ignore
          visibility={
            router.pathname === "/about" || isWelcomePage(router.pathname)
              ? "hidden"
              : ""
          }
          px={30}
        >
          Create
        </Button>
      </Flex>
      <ConfessionModal isOpen={isOpen} onClose={onClose} />
    </Box>
  );
};

export default Navbar;
