// pages/about.tsx
import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import { Flex, Box } from "@chakra-ui/react"

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>About Confession Wall</title>
      </Head>
      <Box padding="10px" textAlign='center'>
        <Box fontSize={24} my="20px">About Confession Wall</Box>
        <Box mt="10px" mb="3rem">
          Personal project
          <Box>Stack: </Box>
          <Box mt="10px" mb="3rem">
            <Box>
              <li>Prisma</li>
              <li>Vite</li>
              <li>SCSS</li>
              <li>Vue</li>
            </Box>
          </Box>
          <div style={{marginBottom: "2rem"}}>
            Email: <a href="mailto:daprogrammer1@gmail.com">Clark</a>
          </div>
          <div>
            Back to 
            {" "} 
            <Link href="/home">
              <span className="linkToHome">Confession Wall</span>
            </Link>
            <style jsx>{`
              .linkToHome {
                color: #009EFF;
                transition: filter 100ms;
              }
              .linkToHome:hover {
                filter: brightness(.6);
              }
            `}
            </style>
          </div>
        </Box>
      </Box>
    </div>
  )
}

export default About

// pages/about.vue
<script setup lang="ts">
import { h } from 'vue';
import { Envelope } from '@vicons/fa';
import { NButton } from 'naive-ui';
import nuxt from 'assets/nuxt.svg';
import prisma from 'assets/prisma.svg';
import naiveui from 'assets/naive-ui.svg';

const stack: StackItem[] = [
	{
		name: "Nuxt",
		alt: "nuxt",
		image: nuxt,
		width: 40
	},
	{
		name: "Prisma",
		alt: "prisma",
		image: prisma
	},
	{
		name: "Naive UI",
		alt: "naive ui",
		image: naiveui
	}
];

function openEmail() {
	document.location.href = "mailto:mjohncl4rk@gmail.com";
}

useHead({
	title: "About"
});

</script>
<template>
	<div class="main">
		<div class="about">About Confession Wall</div>
		<div>Personal project</div>
		<div>Stack used:</div>
		<div class="stack">
			<StackItem
				v-for="x, i in stack"
				:key="i"
				:image="x.image"
				:alt="x.alt"
				:name="x.name"
				:width="x.width"
			/>
		</div>
		<n-button
			class="button"
			:render-icon="() => h(Envelope)"
			type="primary"
			@click="openEmail"
		>
			Email me
		</n-button>
		<div class="back-to">
			Back to <NuxtLink to="/home">Confession Wall</NuxtLink>
		</div>
	</div>
</template>

<style lang="scss" scoped>
@use '../styles/animations' as an;

.main {
	text-align: center;
	margin-block: 2.5rem;
	.about {
		font-size: 1.5rem;
		margin-block: 1.5rem;
	}
	.button {
		margin-block: 2rem;
	}
	.link-to {
		margin-block: 1rem;
	}
}

a {
	color: #0071df;
	@include an.onhover-link(#0071df);
	text-decoration: none;
}

</style>
