// pages/welcome.vue
<script lang="ts" setup>
import { NButton } from 'naive-ui';

const router = useRouter();
function goToHome() {
	router.push("/home");
}

useHead({
	title: "Welcome"
});
</script>

<template>
	<div>
		<div style="font-weight: bold;">Welcome to Confession Wall</div>
		<n-button
			type="primary"
			strong
			color="#E2E8F0"
			text-color="black"
			@click="goToHome"
		>
			Create yours now
		</n-button>
	</div>
</template>

<style scoped>
div {
	display: grid;
	place-items: center;
}
</style>

// pages/welcome.tsx
import type { NextPage } from "next"
import Head from 'next/head'
import { Button, Flex, Box } from "@chakra-ui/react"
import { useRouter } from "next/router"

const welcome: NextPage = () => {
  const router = useRouter()
  return (
    <Flex flexDirection='column' alignItems='center'>
      <Head>
        <title>Welcome</title>
      </Head>
      <Box fontWeight='bold'>Welcome to Confession Wall</Box>
      <Button onClick={() => router.push("/home")}>Create yours now</Button> 
      <Box color='red' mt={14}>
        Notice: Unfinished. May not work as expected
      </Box>     
    </Flex>
  )
}

export default welcome
